#请允许广告在启动时输出到后台，因为这是MCBBS唯一允许的广告位；但是为了用户着想，任然保留了关闭接口
#有关广告的版规
#3-1: 只有原创插件可以拥有广告宣传,但只允许向后台输出宣传 不允许刷屏。
#  强调：不允许在帖子内宣传，广告的内容仅允许插件定制，若广告被证实为诈骗或者其他违法违规行为，警告删帖处理，情节严重的予以封禁。
#  强调：索要评分仅可以在帖子内出现，禁止在后台出现。更不允许以评分等论坛操作为前提，提供相关的技术服务（开发者有权选择自己是否向用户提供技术帮助，但是不能以在评分后才有这样条件的为前提。）发现者删帖警告处理。构成刷分行为的按照论坛总版规处理。对于规定颁布以前的未整改的插件。分类不合格，扣分2人气20金粒直至整改完成。（2018-2-6）。
#  广告内容需要符合《中华人民共和国广告法》，禁止使用贬低他人的字眼例如：最好，最便宜等。否则予以警告删帖处理。
#  若插件为粗制滥造或过于简单，且大幅度宣传定制等信息，视情况予以最低扣分2人气20金粒的处罚并删帖处理，如果贴内出现违规宣传，则予以删帖，并且视数量予以发卡，最低扣分2人气20金粒10绿宝石2贡献的处罚，若为多贴（大于2)则最低7天的封禁。严重者永久禁言（广告机）。
start-ad: true

#插件语言
lang: zh_CN

#启用哪些API（需要装有对应插件，否则会出错）
API:
  placeholderAPI: false

#破坏掉刷怪笼是否返回物品（true即返回，false即不返回）
dig-return:
  #创造模式返还（此项目受下面权限的影响）
  CREATIVE: false
  #权限（可以自定义为自己服务器的权限）
  permissions:
    myspawner.user.default: false
    myspawner.user.vip: true

#插件命令设置（错误提示请转到languages文件夹）
commands-settings:
  #简洁帮助          子命令名称           子命令简洁帮助
  clearly-help: "&a{sub-command-name} = {sub-command-help}"
  #完整帮助
  fully-help:
    start:
      #             子命令名称
      - "&a=============================="
    end:
      - "&a=============================="